#!/usr/bin/env sh
# ============================================================================
# 🚀 QUICK START: TEST STATISTICS API - SMARTSPENDER
# ============================================================================

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  🚀 QUICK START - TEST STATISTICS API                     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Detect OS
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "cygwin" || "$OSTYPE" == "win32" ]]; then
    OS="windows"
else
    OS="unix"
fi

echo "📋 HỆ THỐNG: $OS"
echo ""
echo "===== TERMINAL 1: BACKEND ====="
echo ""
echo "cd F:/BTL_CNPM/smartspender/SmartSpender/backend"
echo "npm install"
echo "npm run dev"
echo ""
echo "⏳ Chờ cho đến khi thấy: 'Server running on port 3000'"
echo ""
echo ""

echo "===== TERMINAL 2: TEST BACKEND API ====="
echo ""

if [ "$OS" == "windows" ]; then
    echo "PowerShell:"
    echo "cd F:/BTL_CNPM/smartspender/SmartSpender"
    echo ".\TEST_API_STATISTICS.ps1"
else
    echo "Bash:"
    echo "cd F:/BTL_CNPM/smartspender/SmartSpender"
    echo "chmod +x TEST_API_STATISTICS.sh"
    echo "./TEST_API_STATISTICS.sh"
fi

echo ""
echo "⏳ Chờ kết quả test:"
echo "   ✅ Backend Connection: SUCCESS"
echo "   ✅ Authentication: SUCCESS"
echo "   📊 Statistics API Tests: X PASSED"
echo ""
echo ""

echo "===== TERMINAL 3: MOBILE ====="
echo ""
echo "cd F:/BTL_CNPM/smartspender/SmartSpender/mobile"
echo ""
echo "Option A: Dùng Android Emulator"
echo "  flutter run"
echo ""
echo "Option B: Dùng iOS Simulator"
echo "  flutter run -d iPhone_14"
echo ""
echo "Option C: Chỉ định device"
echo "  flutter devices"
echo "  flutter run -d <DEVICE_ID>"
echo ""
echo "⏳ Chờ app khởi động"
echo ""
echo ""

echo "===== TEST FLOW TRÊN MOBILE ====="
echo ""
echo "1️⃣  Login"
echo "    Email: test@smartspender.com"
echo "    Password: Test@123456"
echo ""
echo "2️⃣  Nhấn tab 'Thống kê' (Statistics)"
echo ""
echo "3️⃣  Xác thực KPI Cards"
echo "    ✅ Total Expense = Backend API response"
echo "    ✅ Total Income = Backend API response"
echo "    ✅ Balance = Backend API response"
echo ""
echo "4️⃣  Test Period Picker"
echo "    ✅ Pull to refresh hoặc chọn tháng khác"
echo "    ✅ Data cập nhật đúng"
echo ""
echo "5️⃣  Scroll xuống kiểm tra:"
echo "    ✅ Category Breakdown"
echo "    ✅ Recent Transactions"
echo ""
echo ""

echo "===== TROUBLESHOOTING ====="
echo ""
echo "❌ Backend không start:"
echo "   → MongoDB phải running (mongod)"
echo "   → Kiểm tra .env có PORT=3000"
echo ""
echo "❌ 401 Unauthorized:"
echo "   → Token hết hạn, login lại"
echo "   → Check Authorization header: Bearer <TOKEN>"
echo ""
echo "❌ Mobile không kết nối backend:"
echo "   → Android emulator: 10.0.2.2:3000"
echo "   → iOS simulator: localhost:3000"
echo "   → Physical device: 192.168.x.x:3000 (update AppConfig)"
echo ""
echo "❌ Statistics API return 0 values:"
echo "   → Có transaction cho month/year này chưa?"
echo "   → Check MongoDB: db.transactions.find({})"
echo ""
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  ✅ Ready to Test!                                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
